### ISSUE TITLE
Error when trying to write to DB.

### ISSUE THREAD

**Issue by Roger-Heathcote** [Roger-Heathcote/image-cache#5]
2021-09-22T15:13:01.823Z	f88bbf5a-72e9-4d5e-ae10-8a80044d5525	ERROR	Invoke Error 	
{
    "errorType": "AccessDeniedException",
    "errorMessage": "User: arn:aws:sts::703300139815:assumed-role/ImageCacheStack-addLambdaHandlerServiceRole37B65F5-1V0RGWG3AC93S/ImageCacheStack-addLambdaHandler9017B0E5-OfLEFbYohQEu is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:eu-west-2:703300139815:table/image-cache",
    "code": "AccessDeniedException",
    "message": "User: arn:aws:sts::703300139815:assumed-role/ImageCacheStack-addLambdaHandlerServiceRole37B65F5-1V0RGWG3AC93S/ImageCacheStack-addLambdaHandler9017B0E5-OfLEFbYohQEu is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:eu-west-2:703300139815:table/image-cache",
    "time": "2021-09-22T15:13:01.822Z",
    "requestId": "N5LEURO9D7QE91JDEKCABHN5M3VV4KQNSO5AEMVJF66Q9ASUAAJG",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 16.59556676200964,
    "stack": [
        "AccessDeniedException: User: arn:aws:sts::703300139815:assumed-role/ImageCacheStack-addLambdaHandlerServiceRole37B65F5-1V0RGWG3AC93S/ImageCacheStack-addLambdaHandler9017B0E5-OfLEFbYohQEu is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:eu-west-2:703300139815:table/image-cache",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}

**Comment by Roger-Heathcote** [comment]
Fixed in 9eb3576a11fa2d82dc05f2dfe889e20bd77013a1
